.PHONY: clean All

All:
	@echo "----------Building project:[ casting - Debug ]----------"
	@cd "casting" && "$(MAKE)" -f  "casting.mk"
clean:
	@echo "----------Cleaning project:[ casting - Debug ]----------"
	@cd "casting" && "$(MAKE)" -f  "casting.mk" clean
